### ISSUE TITLE
Trigger ssh commands when i press a button

### ISSUE THREAD

**Issue by j4ckp0t85** [nopnop2002/esp-idf-ssh-client#2]
Hello, i have tried your solution with an esp32 devkit v1 (30 pins) and works fine.
Noob question here. 
I would like to add the logic to trigger the ssh commands you launch in the main function every time a button is pushed down.
Not mandatory but would be good if a led will light up when i press down the button.
So basically define two gpio pins: one related to the button pression and the other to the led (that pass through the resistor).
Of course i need to connect also the ground (no code logic needed for this). 

In the attachment the breadboard i have prepared with no connections yet to the esp32 and the pinout schema that should correspond to my board. 

![ESP32-DOIT-DEV-KIT-v1-pinout-mischianti](https://user-images.githubusercontent.com/36902097/157818769-0451cb4a-3341-4ee4-aca4-44d1c2abd60d.png)

![20220311_075841](https://user-images.githubusercontent.com/36902097/157818832-977d1608-a194-41e9-b96f-1e497e588c0e.jpg)

**Comment by nopnop2002** [comment]
This sample is useful for button input from GPIO.

https://github.com/espressif/esp-idf/tree/master/examples/peripherals/gpio/generic_gpio

**Comment by j4ckp0t85** [comment]
Ok thanks, i need to find some spare time to study on it :)
Talking about code, I expect to copy your routine in the 
 gpio_task_example infinite loop. 

Hint welcome for wires connections to the button and the led. 
the pin numbers in the table are related to Gpio numbers? So for example CONFIG_GPIO_OUTPUT_0 that refer to pin 8 means GPIO8?

**Comment by nopnop2002** [comment]
>i need to find some spare time to study on it :)

Yes.
I totally agree with you.

>So for example CONFIG_GPIO_OUTPUT_0 that refer to pin 8 means GPIO8?

Yes.

Once you understand how to use gpio and how to use ssh, it is easy to run ssh in gpio_task_example.

In addition, you need to understand a little about how to use xQueue.

**Comment by j4ckp0t85** [comment]
This is the part that confuse me mostly

Connect CONFIG_GPIO_OUTPUT_0 with CONFIG_GPIO_INPUT_0

Connect CONFIG_GPIO_OUTPUT_1 with CONFIG_GPIO_INPUT_1

Generate pulses on CONFIG_GPIO_OUTPUT_0/1, that triggers interrupt on CONFIG_GPIO_INPUT_0/1

That seems to be an internal "bridge" connection wires between esp32 gpio pins.

How do i wire to my button pin and the resistor pin that lights up the diode?

**Comment by nopnop2002** [comment]
>That seems to be an internal "bridge" connection wires between esp32 gpio pins.

No.

CONFIG_GPIO_OUTPUT_0 is OUTPUT gpio.
On the ESP32, the default for CONFIG_GPIO_OUTPUT_0 is GPIO18.
You can change this using menuconfig.
Connect the LED to GPIO18.

CONFIG_GPIO_INPUT_0 is INPUT gpio. 
On the ESP32, the default for CONFIG_GPIO_INPUT_0 is GPIO4.
Connect the Button to GPIO4.


LED is turned on / off by button input.

**Comment by j4ckp0t85** [comment]
Ok, now it's clear. Thanks, i will try to implement it on spare time

**Comment by j4ckp0t85** [comment]
Done 👍  thanks friend
